# Generated by Django 2.1.5 on 2019-02-15 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200)),
                ('lieux', models.CharField(max_length=200)),
                ('placeMax', models.IntegerField()),
                ('date', models.DateField(default='2019-02-13')),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoDeGroupe', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceVendu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresseMail', models.EmailField(max_length=254)),
                ('nombrePlace', models.IntegerField(default=1)),
                ('place', models.CharField(max_length=200)),
                ('concert', models.ForeignKey(default=-1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='concertPlaceVendu', to='app.Concert')),
            ],
        ),
        migrations.CreateModel(
            name='TypePlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200)),
                ('prixPlace', models.IntegerField(default=0)),
                ('concert', models.ForeignKey(default=-1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='concertTypePlace', to='app.Concert')),
            ],
        ),
        migrations.AddField(
            model_name='concert',
            name='groupe',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Groupe', to='app.Groupe'),
        ),
    ]
