# Generated by Django 2.1.5 on 2019-02-11 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200)),
                ('lieux', models.CharField(max_length=200)),
                ('placeMax', models.IntegerField()),
                ('groupe', models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, related_name='groupe', to='app.Groupe')),
            ],
        ),
    ]
