# Generated by Django 2.1.5 on 2019-02-11 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_concert'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceVendu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresseMail', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=50)),
                ('concert', models.ForeignKey(default='none', on_delete=django.db.models.deletion.DO_NOTHING, related_name='concert', to='app.Concert')),
            ],
        ),
    ]
