# Generated by Django 2.1.5 on 2019-02-13 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_concert_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='place',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='TypePlace', to='app.TypePlace'),
        ),
        migrations.AlterField(
            model_name='placevendu',
            name='concert',
            field=models.ForeignKey(default='none', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='concert', to='app.Concert'),
        ),
    ]
