# Generated by Django 2.1.5 on 2019-02-13 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190213_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='place',
        ),
    ]
