# Generated by Django 2.1.5 on 2019-02-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_placevendu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placevendu',
            name='place',
            field=models.IntegerField(),
        ),
    ]
