# Generated by Django 2.1.7 on 2019-03-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190312_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placevendu',
            old_name='adresseMail',
            new_name='adresse_mail',
        ),
        migrations.RenameField(
            model_name='placevendu',
            old_name='nombrePlace',
            new_name='nombre_place',
        ),
        migrations.RenameField(
            model_name='typeplace',
            old_name='place',
            new_name='nom',
        ),
    ]
