# Generated by Django 2.1.5 on 2019-02-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190211_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='prix',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
