# Generated by Django 2.1.7 on 2019-03-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190312_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeplace',
            old_name='prixPlace',
            new_name='prix',
        ),
    ]
