# Generated by Django 2.1.6 on 2019-02-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190211_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='prix',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
