# Generated by Django 2.1.5 on 2019-02-13 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_concert_prix'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypePlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200)),
                ('prixPlace', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='placevendu',
            name='place',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.DO_NOTHING, related_name='TypePlace', to='app.TypePlace'),
        ),
    ]
