# Generated by Django 2.1.5 on 2019-02-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190213_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placevendu',
            name='adresseMail',
            field=models.EmailField(max_length=254),
        ),
    ]
