# Generated by Django 2.1.5 on 2019-02-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190213_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='placevendu',
            name='nombrePlace',
            field=models.IntegerField(default=1),
        ),
    ]
