# Generated by Django 2.1.5 on 2019-02-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_placevendu_nombreplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='prix',
        ),
    ]
