# Generated by Django 2.1.5 on 2019-02-13 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_concert_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='date',
            field=models.DateField(default='2019-02-13'),
        ),
        migrations.AlterField(
            model_name='placevendu',
            name='place',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.DO_NOTHING, related_name='PlaceVendu', to='app.TypePlace'),
        ),
    ]
